# Site settings
title: Angi Welsch
thumb_small: "/thumbs/small"
thumb_large: "/thumbs/large"
url: "" # the base hostname & protocol for your site
twitter_username: gavenheim
github_username: gavenheim

# Build settings
markdown: kramdown
exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
  - gulpfile.*
  - package.json
  - README.md
  - gulp

mini_magick:
  thumbnail:
      source: images/uploads/
      destination: thumbs/small/images/uploads/
      resize: "630"
  large:
      source: images/uploads/
      destination: thumbs/large/images/uploads/
      resize: "x1304"
      
