---
upload_path: "/images/uploads"
frontmatter_file_url_template: "/images/uploads"
body_file_url_template: "/uploads/:year:/:month:/:day:"
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
collections: 
